// Beat / tempo / loudness analysis on synthetic tracks. No music files: every
// signal is generated by ffmpeg's lavfi aevalsrc and piped straight into memory.
import { spawnSync } from "node:child_process";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { analysePcm, decode, loudness, pickStart, renderDuration } from "../scripts/beats.mjs";
import { withTimingFile } from "../scripts/lib.mjs";
import { planVideo } from "../src/engine/plan.ts";
import { videoSchema } from "../src/engine/schema.ts";

const KIT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const hasFfmpeg = spawnSync("ffmpeg", ["-version"], { stdio: "ignore" }).status === 0;
const skip = hasFfmpeg ? false : "ffmpeg not installed";

/**
 * A drum-machine loop: kick (60 Hz body + click) on every beat, louder on beat
 * one of each bar, noise hi-hats on the off-beats (the classic trap for
 * double-time readings), starting at `offset` seconds.
 */
const drums = ({ bpm, offset = 0.137, seconds = 24, level = "1" }) => {
  const p = 60 / bpm;
  const m = `mod(t-${offset},${p})`;
  const h = `mod(t-${offset}-${p / 2},${p})`;
  const accent = `(1+0.8*lt(mod(t-${offset},${4 * p}),${p / 2}))`;
  const kick = `${accent}*(0.7*sin(2*PI*60*${m})*exp(-12*${m})+0.3*sin(2*PI*1800*${m})*exp(-150*${m}))`;
  const hat = `0.15*(2*random(0)-1)*exp(-60*${h})`;
  const expr = `gte(t,${offset})*(${level})*(${kick}+${hat})*0.5`;
  return ["-f", "lavfi", "-i", `aevalsrc=exprs='${expr}':s=22050:d=${seconds}`];
};

const nearestError = (ms, offsetMs, periodMs) => {
  const k = Math.round((ms - offsetMs) / periodMs);
  return Math.abs(ms - (offsetMs + k * periodMs));
};

for (const bpm of [90, 120, 128]) {
  test(`detects ${bpm} BPM within ±1 BPM, beats and downbeats within 30 ms`, { skip }, () => {
    const offset = 0.137;
    const a = analysePcm(decode(drums({ bpm, offset })));
    assert.equal(a.rhythmic, true);
    assert.ok(Math.abs(a.bpm - bpm) <= 1, `got ${a.bpm} BPM`);

    const period = 60000 / bpm;
    const expected = Math.floor((24 - offset) / (period / 1000));
    assert.ok(a.beats.length >= expected * 0.9, `only ${a.beats.length} of ~${expected} beats found`);
    const worst = Math.max(...a.beats.map((b) => nearestError(b, offset * 1000, period)));
    assert.ok(worst <= 30, `a beat is ${worst.toFixed(1)} ms off the grid`);

    assert.ok(a.downbeats.length >= Math.floor(expected / 4) - 1, `only ${a.downbeats.length} downbeats`);
    const bar = Math.max(...a.downbeats.map((b) => nearestError(b, offset * 1000, 4 * period)));
    assert.ok(bar <= 30, `a downbeat is ${bar.toFixed(1)} ms off beat one`);
  });
}

test("fast tracks resolve to their tempo or half of it (an octave), never a 2:3 neighbour", { skip }, () => {
  for (const bpm of [150, 165]) {
    const offset = 0.31;
    const a = analysePcm(decode(drums({ bpm, offset, seconds: 30 })));
    const ratio = a.bpm / bpm;
    assert.ok(Math.abs(ratio - 1) < 0.01 || Math.abs(ratio - 0.5) < 0.01, `${bpm} BPM read as ${a.bpm}`);
    // Every detected beat is a kick (half time skips every other one).
    const inner = a.beats.slice(1, -1);
    const worst = Math.max(...inner.map((b) => nearestError(b, offset * 1000, 60000 / bpm)));
    assert.ok(worst <= 30, `${bpm} BPM: a beat is ${worst.toFixed(1)} ms off the kicks`);
  }
});

test("integrated loudness follows the signal level (EBU R128)", { skip }, () => {
  const sine = (vol) => ["-f", "lavfi", "-i", `sine=frequency=997:sample_rate=48000:duration=5,volume=${vol}`];
  const full = loudness(sine(1));
  const half = loudness(sine(0.5));
  // ffmpeg's sine source peaks at 1/8 (-18 dBFS): a mono 997 Hz sine at that level reads ~-21 LUFS.
  assert.ok(Math.abs(full - -21.1) < 1, `got ${full} LUFS`);
  assert.ok(Math.abs(full - half - 6.02) < 0.3, `halving the level changed loudness by ${(full - half).toFixed(2)} dB`);
});

test("music starts on the bar that opens the most energetic stretch", { skip }, () => {
  // 120 BPM: quiet intro to 16 s, full energy 16-40 s, quiet outro.
  const level = "0.2+0.8*between(t,16,40)";
  const a = analysePcm(decode(drums({ bpm: 120, offset: 0, seconds: 48, level })));
  const { startMs, covers } = pickStart({ rms: a.rms, downbeatsMs: a.downbeats, beatsMs: a.beats, durationMs: a.durationMs, needMs: 20000 });
  assert.equal(covers, true);
  assert.ok(Math.abs(startMs - 16000) <= 30, `started at ${startMs} ms`);
  assert.ok(a.downbeats.includes(startMs), "start is a downbeat");
});

test("a track shorter than the video starts at 0 and reports it must loop", { skip }, () => {
  const a = analysePcm(decode(drums({ bpm: 100, offset: 0, seconds: 10 })));
  const r = pickStart({ rms: a.rms, downbeatsMs: a.downbeats, beatsMs: a.beats, durationMs: a.durationMs, needMs: 30000 });
  assert.deepEqual(r, { startMs: 0, covers: false });
});

test("free-time music (pads, drones, noise) reports no beat; a kick buried under a pad still does", { skip }, () => {
  const lav = (src) => ["-f", "lavfi", "-i", src];
  const pad = "0.25*sin(2*PI*220*t)*(0.6+0.4*sin(2*PI*0.05*t))+0.15*sin(2*PI*330*t)+0.1*sin(2*PI*440.5*t)";
  const kick = "(0.7*sin(2*PI*60*mod(t,0.5))*exp(-12*mod(t,0.5))+0.3*sin(2*PI*1800*mod(t,0.5))*exp(-150*mod(t,0.5)))";
  const drone = analysePcm(decode(lav(`aevalsrc=exprs='${pad}':s=22050:d=30`)));
  assert.equal(drone.rhythmic, false, `a sustained pad read as ${drone.bpm} BPM (pulse ${drone.pulse})`);
  const noise = analysePcm(decode(lav("anoisesrc=d=30:c=pink:r=22050:a=0.3:seed=7")));
  assert.equal(noise.rhythmic, false, `pink noise read as ${noise.bpm} BPM (pulse ${noise.pulse})`);
  // A kick 20 dB under the pad still carries the beat.
  const buried = analysePcm(decode(lav(`aevalsrc=exprs='${pad}+0.1*${kick}':s=22050:d=30`)));
  assert.equal(buried.rhythmic, true, `pulse ${buried.pulse}`);
  assert.ok(Math.abs(buried.bpm - 120) <= 1, `got ${buried.bpm} BPM`);
});

test("MP3 keeps its encoder delay and padding, as the renderer plays them; loops use the renderer's length", { skip }, async () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "motion-kit-music-"));
  try {
    const src = drums({ bpm: 120, offset: 0.137, seconds: 12 });
    const mp3 = path.join(tmp, "t.mp3");
    const ogg = path.join(tmp, "t.ogg");
    const wav = path.join(tmp, "t.wav");
    const encode = (out, codec, rate = 44100) => spawnSync("ffmpeg", ["-v", "error", "-y", ...src, "-ar", String(rate), ...codec, out]).status === 0;
    assert.ok(encode(wav, []));
    const ref = analysePcm(decode(wav));
    assert.equal(await renderDuration(wav), 12000);

    if (encode(mp3, ["-c:a", "libmp3lame", "-b:a", "192k"])) {
      // LAME: 576 samples encoder delay + 529 decoder delay ahead of the music.
      const delayMs = (1105 / 44100) * 1000;
      const a = analysePcm(decode(mp3));
      const shifts = a.beats.map((b) => b - ref.beats.reduce((best, r) => (Math.abs(r - b) < Math.abs(best - b) ? r : best))).sort((x, y) => x - y);
      const shift = shifts[shifts.length >> 1];
      assert.ok(Math.abs(shift - delayMs) < 3, `MP3 beats are ${shift.toFixed(1)} ms after the WAV's (expected ${delayMs.toFixed(1)})`);
      const played = await renderDuration(mp3);
      assert.ok(played > 12000 + delayMs, `renderer length ${played} ms includes the priming and padding`);
      assert.ok(Math.abs(played - a.durationMs) <= 1, `decoded ${a.durationMs} ms vs renderer ${played} ms`);
    }
    // Ogg/Opus: mediabunny's length (what the renderer loops on) is ~13 ms longer than ffmpeg's decode.
    if (encode(ogg, ["-c:a", "libopus"], 48000)) {
      const played = await renderDuration(ogg);
      assert.ok(played !== null && Math.abs(played - 12000) < 40, `Ogg length ${played} ms`);
    }
    assert.equal(await renderDuration(path.join(tmp, "missing.mp3")), null);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test("npm run music refuses to run without a track", () => {
  const r = spawnSync(process.execPath, ["scripts/music.mjs", "specs/claude-reel.json"], { cwd: KIT, encoding: "utf8" });
  assert.equal(r.status, 1);
  assert.match(r.stderr, /--track/);
});

test("npm run music: analyses a track, writes the beats file and links it in the spec", { skip }, () => {
  // Quiet intro to 12 s, full energy 12-40 s: the start lands at the 12 s bar (or a beat's pickup before it).
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "motion-kit-music-"));
  const name = `zz-test-${process.pid}`;
  const musicDir = path.join(KIT, "public", "music");
  const hadDir = fs.existsSync(musicDir);
  const made = [path.join(musicDir, `${name}.wav`), path.join(musicDir, `${name}.beats.json`)];
  try {
    const track = path.join(tmp, `${name}.wav`);
    const input = drums({ bpm: 120, offset: 0, seconds: 40, level: "0.15+0.85*between(t,12,40)" });
    assert.equal(spawnSync("ffmpeg", ["-v", "error", "-y", ...input, track]).status, 0);
    const specFile = path.join(tmp, "spec.json");
    const scenes = [
      { type: "title", headline: "Turn words into *motion*" },
      { type: "stat", value: "87%", label: "of viewers watch *without sound*" },
      { type: "list", title: "What you get", items: ["Timing", "Sound", "Colour"], style: "checks" },
      { type: "cta", action: "Try it", sub: "Free for creators" },
    ];
    fs.writeFileSync(specFile, JSON.stringify({ format: "reel", theme: "midnight", scenes }));

    const r = spawnSync(process.execPath, ["scripts/music.mjs", specFile, "--track", track, "--volume", "0.25"], { cwd: KIT, encoding: "utf8" });
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /120\.0 BPM/);
    assert.match(r.stdout, /Long enough/);

    const spec = JSON.parse(fs.readFileSync(specFile, "utf8"));
    assert.equal(spec.audio.music, `music/${name}.wav`);
    assert.equal(spec.audio.beats, `music/${name}.beats.json`);
    assert.equal(spec.audio.musicVolume, 0.25);
    assert.equal(spec.audio.beatGrid, undefined, "the grid stays in the beats file, not the spec");
    assert.ok(fs.existsSync(made[0]), "the track is copied into public/music/");

    const data = JSON.parse(fs.readFileSync(made[1], "utf8"));
    assert.deepEqual(Object.keys(data).sort(), ["beats", "bpm", "downbeats", "durationMs", "lufs", "startMs", "track"]);
    assert.ok(Math.abs(data.bpm - 120) <= 1);
    assert.equal(data.durationMs, 40000);
    assert.ok(Number.isFinite(data.lufs));
    assert.equal(data.startMs, Math.round(spec.audio.musicStart * 1000));
    assert.ok(data.startMs >= 12000 - 500 - 30 && data.startMs <= 12030, `started at ${data.startMs} ms`);

    // The planner picks the grid up from the file and lands cuts on it.
    const plan = planVideo(videoSchema.parse(withTimingFile(spec)));
    assert.ok(plan.music.beats.length > 10);
    assert.ok(plan.scenes.filter((s) => s.onBeat !== undefined).length >= 2, "cuts land on the beat");
  } finally {
    for (const f of made) fs.rmSync(f, { force: true });
    if (!hadDir && fs.existsSync(musicDir) && !fs.readdirSync(musicDir).length) fs.rmdirSync(musicDir);
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});
