"""Synthesise the kit's sound effects and grain texture.

Everything in public/sfx and public/textures is generated by this script, so
there is no third-party licence to track. Re-run with:

    python3 tools/gen-assets.py   (needs numpy + pillow)
"""

import pathlib
import wave

import numpy as np
from PIL import Image

SR = 48000
ROOT = pathlib.Path(__file__).resolve().parent.parent / "public"
rng = np.random.default_rng(7)


def t(seconds):
    return np.arange(int(seconds * SR)) / SR


def env(n, attack, release, curve=3.0):
    """Attack/release envelope in seconds with exponential tails."""
    e = np.ones(n)
    a = max(1, int(attack * SR))
    r = max(1, int(release * SR))
    e[:a] = np.linspace(0, 1, a) ** 2
    e[-r:] *= np.exp(-curve * np.linspace(0, 1, r)) * np.linspace(1, 0, r) ** 0.5
    return e


def sweep_bandpass(x, f_start, f_peak, f_end, q=1.4):
    """Time-varying biquad band-pass; centre glides start -> peak -> end."""
    n = len(x)
    half = n // 2
    freqs = np.concatenate([
        np.geomspace(f_start, f_peak, half),
        np.geomspace(f_peak, f_end, n - half),
    ])
    y = np.zeros(n)
    x1 = x2 = y1 = y2 = 0.0
    for i in range(n):
        w0 = 2 * np.pi * freqs[i] / SR
        alpha = np.sin(w0) / (2 * q)
        b0, b2 = alpha, -alpha
        a0, a1, a2 = 1 + alpha, -2 * np.cos(w0), 1 - alpha
        out = (b0 * x[i] + b2 * x2 - a1 * y1 - a2 * y2) / a0
        x2, x1 = x1, x[i]
        y2, y1 = y1, out
        y[i] = out
    return y


def lowpass(x, cutoff):
    a = np.exp(-2 * np.pi * cutoff / SR)
    y = np.zeros_like(x)
    acc = 0.0
    for i, v in enumerate(x):
        acc = (1 - a) * v + a * acc
        y[i] = acc
    return y


def stereo(mono, pan_from=0.0, pan_to=0.0):
    pan = np.linspace(pan_from, pan_to, len(mono))
    left = mono * np.cos((pan + 1) * np.pi / 4)
    right = mono * np.sin((pan + 1) * np.pi / 4)
    return np.stack([left, right], axis=1)


def write(name, data, peak_db=-3.0):
    if data.ndim == 1:
        data = stereo(data)
    data = data / (np.max(np.abs(data)) + 1e-9) * 10 ** (peak_db / 20)
    path = ROOT / "sfx" / f"{name}.wav"
    path.parent.mkdir(parents=True, exist_ok=True)
    pcm = (data * 32767).astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())
    print(f"{path.relative_to(ROOT.parent)}  {len(data) / SR:.2f}s")


def whoosh(seconds=0.55, lo=260, hi=2600, end=700, pan=(-0.6, 0.6)):
    n = len(t(seconds))
    noise = rng.standard_normal(n)
    body = sweep_bandpass(noise, lo, hi, end, q=1.2)
    air = sweep_bandpass(noise, lo * 3, hi * 2.2, end * 2, q=2.5) * 0.35
    shape = np.sin(np.linspace(0, np.pi, n)) ** 1.6
    return stereo((body + air) * shape, *pan)


def pop():
    tt = t(0.16)
    f = 950 * np.exp(-tt * 28) + 260
    phase = 2 * np.pi * np.cumsum(f) / SR
    tone = np.sin(phase) * np.exp(-tt * 34)
    click = rng.standard_normal(len(tt)) * np.exp(-tt * 900) * 0.4
    return tone + click


def click():
    tt = t(0.05)
    burst = rng.standard_normal(len(tt)) * np.exp(-tt * 260)
    return sweep_bandpass(burst, 3200, 4200, 3000, q=3.0) + np.sin(2 * np.pi * 1800 * tt) * np.exp(-tt * 300) * 0.3


def impact():
    tt = t(1.1)
    f = 95 * np.exp(-tt * 3.5) + 38
    phase = 2 * np.pi * np.cumsum(f) / SR
    sub = np.sin(phase) * np.exp(-tt * 3.2)
    thump = lowpass(rng.standard_normal(len(tt)), 900) * np.exp(-tt * 22) * 3.0
    tail = lowpass(rng.standard_normal(len(tt)), 3000) * np.exp(-tt * 6) * 0.25
    return np.tanh((sub + thump + tail) * 1.4)


def riser(seconds=1.2):
    tt = t(seconds)
    n = len(tt)
    noise = sweep_bandpass(rng.standard_normal(n), 300, 2500, 6000, q=1.6)
    f = np.geomspace(180, 900, n)
    saw = 2 * ((np.cumsum(f) / SR) % 1.0) - 1
    saw = lowpass(saw, 2500) * 0.25
    shape = np.linspace(0, 1, n) ** 2.2
    shape[-int(0.03 * SR):] *= np.linspace(1, 0, int(0.03 * SR))
    return stereo((noise + saw) * shape, -0.2, 0.2)


def ding():
    tt = t(1.2)
    partials = [(1318.5, 1.0, 3.2), (2637.0, 0.45, 5.0), (3951.0, 0.18, 7.5), (1975.5, 0.25, 4.2)]
    tone = sum(a * np.sin(2 * np.pi * f * tt) * np.exp(-tt * d) for f, a, d in partials)
    return tone * env(len(tt), 0.003, 0.4)


def typing(seconds=2.0, rate=13):
    """A loop of soft key clicks, slightly irregular, for typing animations."""
    n = len(t(seconds))
    out = np.zeros(n)
    k = click()
    pos = 0.0
    while True:
        idx = int(pos * SR)
        if idx + len(k) >= n:
            break
        out[idx:idx + len(k)] += k * rng.uniform(0.45, 1.0)
        pos += 1 / rate * rng.uniform(0.7, 1.3)
    return lowpass(out, 6000)


def swoosh_soft():
    return whoosh(0.4, 400, 1800, 900, pan=(0.3, -0.3)) * 0.8


def grain(size=256, alpha=26):
    noise = rng.normal(128, 64, (size, size)).clip(0, 255).astype(np.uint8)
    rgba = np.stack([noise, noise, noise, np.full_like(noise, alpha)], axis=-1)
    path = ROOT / "textures" / "grain.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(rgba, "RGBA").save(path, optimize=True)
    print(f"{path.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    write("whoosh", whoosh(), -4)
    write("whoosh-soft", swoosh_soft(), -8)
    write("pop", pop(), -5)
    write("click", click(), -9)
    write("impact", impact(), -2)
    write("riser", riser(), -6)
    write("ding", ding(), -6)
    write("typing", typing(), -12)
    grain()
